// RootLayout.tsx
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '../AuthContext';
import ProtectedRoute from '../ProtectedRoute';
import { ReactNode } from 'react';
import Navbar from '@/components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ProtectedRoute>
            <Navbar />
            {children}
          </ProtectedRoute>
        </AuthProvider>
      </body>
    </html>
  );
}
